services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - users

  auth:
    container_name: auth_service
    build:
      context: ./
      dockerfile: auth/Dockerfile
    command: /bin/sh -c "alembic upgrade head && python3 main.py"
    depends_on:
      - auth_db
      - broker
    restart: always
    volumes:
      - ./auth:/app
      - ./env/.env.auth:/app/env/.env.auth
    env_file:
      - env/.env.auth

  auth_db:
    container_name: auth_db_service
    image: postgres:latest
    env_file:
      - env/.env.auth
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  users:
    container_name: users_service
    build:
      context: ./
      dockerfile: users/Dockerfile
    command: /bin/sh -c "alembic upgrade head && ./dumps/run_psql.sh && python3 main.py"
    depends_on:
      - users_db
      - broker
    restart: always
    volumes:
      - ./users:/app
      - ./env/.env.users:/app/env/.env.user
    env_file:
      - env/.env.users

  users_db:
    container_name: users_db_service
    image: postgres:latest
    env_file:
      - env/.env.users
    volumes:
      - users_db_data:/var/lib/postgresql/data

  broker:
    image: rabbitmq:3-management
    container_name: broker_service
    env_file:
      - env/.env.rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - broker_data:/var/lib/rabbitmq

volumes:
  auth_db_data:
  users_db_data:
  broker_data:
