services:
  auth:
    container_name: auth_service
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 80:80
    command: /bin/sh -c 'uvicorn main:app --reload --host 0.0.0.0 --port 80'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/mydatabase
    restart: always
    volumes:
      - ./auth:/app

  db:
    container_name: db_service
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
