[tool.poetry]
name = "42musaev"
version = "0.1.0"
description = ""
authors = ["Askhab Musaev <42musaev@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
